title: Site

columns: 
  - width: 3/4
    sections:
        allcontent:
            type: pages
            headline: Pages
            status: all
            create: default
  - width: 1/4
    sections:
        contactdata:
            type: fields
            fields:
                hero_image:
                    label: Homepage Image
                    type: files
                    multiple: false
                    layout: cards
                headline:
                    label: Footer
                    type: headline
                footer_heading:
                    label: Footer Heading
                    type: text
                footer_subheading:
                    label: Footer Subheading
                    type: text
                footer_company:
                    label: Footer Company Name
                    type: text
                footer_address:
                    label: Footer Address
                    type: textarea
                footer_phone:
                    label: Footer Phone
                    type: text
                footer_fax:
                    label: Footer Fax
                    type: text
                footer_email:
                    label: Footer Email
                    type: text
                footer_menu:
                    label: Footer Menu
                    type: pages
                    subpages: false


